var data = [
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 20, genderOfSender: 0, relationshipToSender: 5, happiness: 0.5},
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 21, genderOfSender: 1, relationshipToSender: 5, happiness: 0.6},
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 22, genderOfSender: 1, relationshipToSender: 6, happiness: 0.65},
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 22, genderOfSender: 1, relationshipToSender: 7, happiness: 0.72},
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 22, genderOfSender: 1, relationshipToSender: 8, happiness: 0.79},
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 22, genderOfSender: 1, relationshipToSender: 10, happiness: 0.52},
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 22, genderOfSender: 1, relationshipToSender: 5, happiness: 0.62},
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 22, genderOfSender: 1, relationshipToSender: 5, happiness: 0.62}, 
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 23, genderOfSender: 1, relationshipToSender: 5, happiness: 0.63},
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 24, genderOfSender: 1, relationshipToSender: 5, happiness: 0.64},
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 25, genderOfSender: 1, relationshipToSender: 5, happiness: 0.66},
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 26, genderOfSender: 1, relationshipToSender: 5, happiness: 0.6},
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 30, genderOfSender: 1, relationshipToSender: 5, happiness: 0.4},
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 30, genderOfSender: 1, relationshipToSender: 5, happiness: 0.5},
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 30, genderOfSender: 1, relationshipToSender: 6, happiness: 0.6},
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 30, genderOfSender: 1, relationshipToSender: 7, happiness: 0.7},
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 30, genderOfSender: 1, relationshipToSender: 8, happiness: 0.8},
{season: 1, dayOfTheWeek: 2, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 18, genderOfSender: 0, relationshipToSender: 7, happiness: 0.6}, 
{season: 1, dayOfTheWeek: 1, currentDate: 18, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 17, genderOfSender: 0, relationshipToSender: 1, happiness: 0.2}, 
{season: 1, dayOfTheWeek: 6, currentDate: 24, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 18, genderOfSender: 1, relationshipToSender: 6, happiness: 0.7}, 
{season: 1, dayOfTheWeek: 7, currentDate: 25, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 24, genderOfSender: 0, relationshipToSender: 4, happiness: 0.6}, 
{season: 1, dayOfTheWeek: 7, currentDate: 25, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 25, genderOfSender: 1, relationshipToSender: 4, happiness: 0.6}, 
{season: 1, dayOfTheWeek: 1, currentDate: 25, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 18, genderOfSender: 1, relationshipToSender: 5, happiness: 0.3}, 
{season: 2, dayOfTheWeek: 7, currentDate: 20, userAge: 18, userGender: 0, socialSuccess: 3, ageOfSender: 20, genderOfSender: 0, relationshipToSender: 6, happiness: 0.5}, 
{season: 2, dayOfTheWeek: 4, currentDate: 29, userAge: 18, userGender: 0, socialSuccess: 4, ageOfSender: 17, genderOfSender: 1, relationshipToSender: 8, happiness: 0.9}, 
{season: 3, dayOfTheWeek: 3, currentDate: 10, userAge: 18, userGender: 0, socialSuccess: 4, ageOfSender: 50, genderOfSender: 0, relationshipToSender: 7, happiness: 0.8}, 
{season: 3, dayOfTheWeek: 4, currentDate: 12, userAge: 18, userGender: 0, socialSuccess: 4, ageOfSender: 18, genderOfSender: 0, relationshipToSender: 8, happiness: 0.7}, 
{season: 4, dayOfTheWeek: 1, currentDate: 15, userAge: 19, userGender: 0, socialSuccess: 4, ageOfSender: 19, genderOfSender: 1, relationshipToSender: 5, happiness: 0.3}, 
{season: 4, dayOfTheWeek: 2, currentDate: 21, userAge: 19, userGender: 0, socialSuccess: 4, ageOfSender: 19, genderOfSender: 0, relationshipToSender: 5, happiness: 0.4}, 
{season: 4, dayOfTheWeek: 1, currentDate: 15, userAge: 19, userGender: 0, socialSuccess: 4, ageOfSender: 25, genderOfSender: 0, relationshipToSender: 4, happiness: 0.3}, 
{season: 4, dayOfTheWeek: 5, currentDate: 29, userAge: 19, userGender: 0, socialSuccess: 4, ageOfSender: 25, genderOfSender: 1, relationshipToSender: 7, happiness: 0.8}, 
{season: 1, dayOfTheWeek: 4, currentDate: 29, userAge: 22, userGender: 1, socialSuccess: 7, ageOfSender: 22, genderOfSender: 1, relationshipToSender: 7, happiness: 0.4}, 
{season: 1, dayOfTheWeek: 7, currentDate: 10, userAge: 22, userGender: 1, socialSuccess: 7, ageOfSender: 20, genderOfSender: 1, relationshipToSender: 4, happiness: 0.2}, 
{season: 1, dayOfTheWeek: 5, currentDate: 13, userAge: 22, userGender: 1, socialSuccess: 7, ageOfSender: 26, genderOfSender: 0, relationshipToSender: 8, happiness: 0.9}, 
{season: 1, dayOfTheWeek: 1, currentDate: 16, userAge: 22, userGender: 1, socialSuccess: 7, ageOfSender: 23, genderOfSender: 0, relationshipToSender: 5, happiness: 0.4}, 
{season: 2, dayOfTheWeek: 2, currentDate: 21, userAge: 22, userGender: 1, socialSuccess: 7, ageOfSender: 18, genderOfSender: 0, relationshipToSender: 6, happiness: 0.3}, 
{season: 2, dayOfTheWeek: 4, currentDate: 29, userAge: 22, userGender: 1, socialSuccess: 7, ageOfSender: 22, genderOfSender: 1, relationshipToSender: 4, happiness: 0.1}, 
{season: 2, dayOfTheWeek: 4, currentDate: 21, userAge: 22, userGender: 1, socialSuccess: 7, ageOfSender: 22, genderOfSender: 1, relationshipToSender: 6, happiness: 0.3}, 
{season: 3, dayOfTheWeek: 3, currentDate: 1, userAge: 22, userGender: 1, socialSuccess: 7, ageOfSender: 24, genderOfSender: 0, relationshipToSender: 3, happiness: 0.1}, 
{season: 3, dayOfTheWeek: 5, currentDate: 15, userAge: 22, userGender: 1, socialSuccess: 7, ageOfSender: 22, genderOfSender: 1, relationshipToSender: 9, happiness: 0.8}, 
{season: 3, dayOfTheWeek: 7, currentDate: 18, userAge: 22, userGender: 1, socialSuccess: 7, ageOfSender: 23, genderOfSender: 0, relationshipToSender: 8, happiness: 0.8}, 
{season: 3, dayOfTheWeek: 6, currentDate: 30, userAge: 22, userGender: 1, socialSuccess: 7, ageOfSender: 20, genderOfSender: 1, relationshipToSender: 6, happiness: 0.3}, 
{season: 3, dayOfTheWeek: 2, currentDate: 3, userAge: 22, userGender: 1, socialSuccess: 7, ageOfSender: 35, genderOfSender: 0, relationshipToSender: 2, happiness: 0.1}, 
{season: 4, dayOfTheWeek: 4, currentDate: 6, userAge: 22, userGender: 1, socialSuccess: 7, ageOfSender: 25, genderOfSender: 1, relationshipToSender: 5, happiness: 0.6}, 
{season: 4, dayOfTheWeek: 3, currentDate: 19, userAge: 22, userGender: 1, socialSuccess: 7, ageOfSender: 19, genderOfSender: 0, relationshipToSender: 6, happiness: 0.6}, 
{season: 4, dayOfTheWeek: 6, currentDate: 22, userAge: 22, userGender: 1, socialSuccess: 7, ageOfSender: 20, genderOfSender: 1, relationshipToSender: 8, happiness: 0.8}, 
{season: 1, dayOfTheWeek: 4, currentDate: 3, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 26, genderOfSender: 0, relationshipToSender: 5, happiness: 0.7},
{season: 1, dayOfTheWeek: 5, currentDate: 11, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 28, genderOfSender: 1, relationshipToSender: 6, happiness: 0.8},
{season: 1, dayOfTheWeek: 2, currentDate: 15, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 32, genderOfSender: 0, relationshipToSender: 4, happiness: 0.4},
{season: 1, dayOfTheWeek: 7, currentDate: 19, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 29, genderOfSender: 0, relationshipToSender: 7, happiness: 0.7},
{season: 2, dayOfTheWeek: 3, currentDate: 21, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 31, genderOfSender: 1, relationshipToSender: 8, happiness: 0.9},
{season: 2, dayOfTheWeek: 5, currentDate: 25, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 30, genderOfSender: 1, relationshipToSender: 9, happiness: 1},
{season: 2, dayOfTheWeek: 1, currentDate: 27, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 27, genderOfSender: 1, relationshipToSender: 2, happiness: 0.2},
{season: 2, dayOfTheWeek: 3, currentDate: 5, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 21, genderOfSender: 0, relationshipToSender: 3, happiness: 0.1},
{season: 2, dayOfTheWeek: 4, currentDate: 11, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 31, genderOfSender: 0, relationshipToSender: 6, happiness: 0.7},
{season: 2, dayOfTheWeek: 7, currentDate: 18, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 29, genderOfSender: 1, relationshipToSender: 5, happiness: 0.7},
{season: 3, dayOfTheWeek: 1, currentDate: 9, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 30, genderOfSender: 0, relationshipToSender: 6, happiness: 0.5},
{season: 3, dayOfTheWeek: 3, currentDate: 19, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 35, genderOfSender: 1, relationshipToSender: 4, happiness: 0.4},
{season: 3, dayOfTheWeek: 4, currentDate: 21, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 31, genderOfSender: 1, relationshipToSender: 5, happiness: 0.6},
{season: 3, dayOfTheWeek: 6, currentDate: 25, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 26, genderOfSender: 1, relationshipToSender: 7, happiness: 0.9}, 
{season: 3, dayOfTheWeek: 7, currentDate: 30, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 29, genderOfSender: 0, relationshipToSender: 5, happiness: 0.5},
{season: 3, dayOfTheWeek: 2, currentDate: 12, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 30, genderOfSender: 1, relationshipToSender: 6, happiness: 0.5},
{season: 4, dayOfTheWeek: 3, currentDate: 15, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 27, genderOfSender: 1, relationshipToSender: 7, happiness: 0.7},
{season: 4, dayOfTheWeek: 3, currentDate: 15, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 31, genderOfSender: 0, relationshipToSender: 7, happiness: 0.6},
{season: 4, dayOfTheWeek: 5, currentDate: 25, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 32, genderOfSender: 1, relationshipToSender: 8, happiness: 0.9},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 26, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3},



{season: 3, dayOfTheWeek: 1, currentDate: 30, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3},
{season: 2, dayOfTheWeek: 1, currentDate: 30, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3},
{season: 1, dayOfTheWeek: 1, currentDate: 30, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3},

{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 29, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 28, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 27, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 26, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 25, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 24, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 23, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3},

{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 8, ageOfSender: 49, genderOfSender: 1, relationshipToSender: 4, happiness: 0.33221},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 7, ageOfSender: 48, genderOfSender: 1, relationshipToSender: 4, happiness: 0.332},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 5, ageOfSender: 47, genderOfSender: 1, relationshipToSender: 4, happiness: 0.31},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 8, ageOfSender: 46, genderOfSender: 1, relationshipToSender: 4, happiness: 0.37},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 7, ageOfSender: 45, genderOfSender: 1, relationshipToSender: 4, happiness: 0.375},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 6, ageOfSender: 44, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3757},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 7, ageOfSender: 43, genderOfSender: 1, relationshipToSender: 4, happiness: 0.375},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 7, ageOfSender: 42, genderOfSender: 1, relationshipToSender: 4, happiness: 0.375},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 5, ageOfSender: 41, genderOfSender: 1, relationshipToSender: 4, happiness: 0.375},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 5, ageOfSender: 40, genderOfSender: 1, relationshipToSender: 4, happiness: 0.375},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 5, ageOfSender: 39, genderOfSender: 1, relationshipToSender: 4, happiness: 0.375},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 5, ageOfSender: 38, genderOfSender: 1, relationshipToSender: 4, happiness: 0.375},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.375},



{season: 1, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 8, ageOfSender: 33, genderOfSender: 1, relationshipToSender: 4, happiness: 0.345},
{season: 2, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 8, ageOfSender: 32, genderOfSender: 1, relationshipToSender: 4, happiness: 0.4234},
{season: 3, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 8, ageOfSender: 29, genderOfSender: 1, relationshipToSender: 4, happiness: 0.332},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 8, ageOfSender: 34, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3767},
{season: 5, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 8, ageOfSender: 37, genderOfSender: 1, relationshipToSender: 4, happiness: 0.34324},
{season: 6, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 8, ageOfSender: 33, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3223},
{season: 7, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 8, ageOfSender: 39, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3223},
{season: 7, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 8, ageOfSender: 33, genderOfSender: 1, relationshipToSender: 4, happiness: 0.379696},

{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 25, userGender: 0, socialSuccess: 8, ageOfSender: 55, genderOfSender: 1, relationshipToSender: 4, happiness: 0.1},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 26, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.12},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 27, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.3},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 28, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.2},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 29, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.23},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 30, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.1},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 29, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.1},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 28, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.2},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 27, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.1},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 26, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.2},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 25, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.1},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 24, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.2},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 23, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.1},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 22, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.1},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 21, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.2},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 20, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.2},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 19, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.19667},
{season: 4, dayOfTheWeek: 1, currentDate: 30, userAge: 18, userGender: 0, socialSuccess: 8, ageOfSender: 50, genderOfSender: 1, relationshipToSender: 4, happiness: 0.123},



]

exports.data = data;
